# -*- coding: utf-8 -*-
"""Pure service that emits a deterministic homepage event impact map."""

from __future__ import annotations

from api.v1.schemas.homepage_event_impact_map import (
    HOMEPAGE_EVENT_IMPACT_MAP_DEFAULT_AS_OF,
    HOMEPAGE_EVENT_IMPACT_MAP_NO_ADVICE_DISCLOSURE,
    HOMEPAGE_EVENT_IMPACT_MAP_SCHEMA_VERSION,
    HomepageEventImpactDataQuality,
    HomepageEventImpactEvent,
    HomepageEventImpactMapResponse,
    HomepageEventImpactWindow,
)


_EVENTS = (
    HomepageEventImpactEvent(
        key="fed_speech_rates_repricing",
        label="联储讲话与利率重新定价",
        observation="政策表述变化可能带动短端利率预期重新定价。",
        affectedAssets=["美债短端", "美元指数", "成长股指数"],
        affectedSectors=["科技", "金融", "公用事业"],
        affectedThemes=["利率敏感资产", "估值折现", "风险偏好"],
        implication="利率预期摇摆时，估值敏感资产需要结合美元与波动线索观察。",
        confidence="needs_confirmation",
        evidenceQuality="placeholder",
        monitorNext=["政策措辞变化", "两年期利率", "美元方向"],
        relatedMacroVariables=["政策利率预期", "实际利率", "美元指数"],
        relatedResearchAreas=["宏观政策路径", "成长估值敏感度"],
    ),
    HomepageEventImpactEvent(
        key="inflation_jobs_print",
        label="通胀与就业数据窗口",
        observation="CPI、PCE或NFP读数可能改变通胀与增长组合的市场理解。",
        affectedAssets=["美债曲线", "美元指数", "股票指数"],
        affectedSectors=["消费", "金融", "科技"],
        affectedThemes=["通胀路径", "增长韧性", "政策预期"],
        implication="数据偏离预期时，市场可能先调整利率与美元，再传导到权益风格。",
        confidence="scenario",
        evidenceQuality="scenario",
        monitorNext=["核心通胀", "就业增速", "工资变化"],
        relatedMacroVariables=["核心通胀", "就业增长", "期限利差"],
        relatedResearchAreas=["通胀粘性", "增长周期"],
    ),
    HomepageEventImpactEvent(
        key="treasury_auction",
        label="美债发行窗口",
        observation="美债发行需求变化可能影响长端利率与期限溢价观察。",
        affectedAssets=["十年期美债", "美元指数", "高久期权益"],
        affectedSectors=["房地产", "科技", "金融"],
        affectedThemes=["期限溢价", "融资条件", "久期敏感度"],
        implication="长端利率压力变化会影响高久期资产与融资成本的研究语境。",
        confidence="needs_confirmation",
        evidenceQuality="placeholder",
        monitorNext=["投标倍数", "长端利率", "期限利差"],
        relatedMacroVariables=["期限溢价", "长端利率", "融资条件"],
        relatedResearchAreas=["债券供需", "权益久期"],
    ),
    HomepageEventImpactEvent(
        key="ai_capex_update",
        label="AI资本开支更新",
        observation="AI资本开支线索可能影响算力链需求与大型科技盈利节奏观察。",
        affectedAssets=["大型科技股", "云计算链", "电力设备"],
        affectedSectors=["软件服务", "半导体", "电力基础设施"],
        affectedThemes=["AI基础设施", "资本开支周期", "算力需求"],
        implication="资本开支线索会把研究焦点推向订单能见度、供给瓶颈与现金流质量。",
        confidence="medium",
        evidenceQuality="placeholder",
        monitorNext=["资本开支指引", "云服务需求", "电力容量约束"],
        relatedMacroVariables=["融资条件", "企业投资", "电力需求"],
        relatedResearchAreas=["AI产业链", "基础设施周期"],
    ),
    HomepageEventImpactEvent(
        key="semiconductor_supply_chain",
        label="半导体供应链线索",
        observation="先进制程、封装或设备供给线索可能改变半导体链条节奏观察。",
        affectedAssets=["半导体指数", "设备企业", "供应链企业"],
        affectedSectors=["半导体", "电子制造", "工业设备"],
        affectedThemes=["先进制程", "供应瓶颈", "库存周期"],
        implication="供应链变化需要同时观察订单、库存、交付周期与终端需求。",
        confidence="medium",
        evidenceQuality="placeholder",
        monitorNext=["交付周期", "库存变化", "设备订单"],
        relatedMacroVariables=["全球制造业", "库存周期", "资本开支"],
        relatedResearchAreas=["半导体周期", "供应链韧性"],
    ),
    HomepageEventImpactEvent(
        key="oil_inventory_geopolitical_premium",
        label="油品库存与地缘风险溢价",
        observation="油品库存变化与地缘风险溢价可能共同影响能源与通胀观察。",
        affectedAssets=["原油", "能源股", "航空运输"],
        affectedSectors=["能源", "交通运输", "化工"],
        affectedThemes=["油价风险溢价", "通胀压力", "供需平衡"],
        implication="油价上行会提高通胀复核权重，也会改变成本敏感行业的研究重点。",
        confidence="scenario",
        evidenceQuality="scenario",
        monitorNext=["库存变化", "运输扰动", "能源价格"],
        relatedMacroVariables=["通胀预期", "能源价格", "实际收入"],
        relatedResearchAreas=["能源供需", "通胀传导"],
    ),
    HomepageEventImpactEvent(
        key="hormuz_strait_path",
        label="霍尔木兹海峡情景",
        observation="海峡通行缓和或紧张情景会影响油价风险溢价与航运观察。",
        affectedAssets=["原油", "航运股", "黄金"],
        affectedSectors=["能源", "航运", "贵金属"],
        affectedThemes=["运输通道", "地缘风险溢价", "避险需求"],
        implication="通行情景改变时，能源、航运与避险资产需要放在同一框架观察。",
        confidence="scenario",
        evidenceQuality="scenario",
        monitorNext=["航运通行", "保险成本", "油价波动"],
        relatedMacroVariables=["能源价格", "通胀预期", "避险需求"],
        relatedResearchAreas=["地缘能源风险", "航运成本"],
    ),
    HomepageEventImpactEvent(
        key="china_policy_event",
        label="中国政策事件",
        observation="政策会议或支持措施线索可能影响内需、地产链与人民币资产观察。",
        affectedAssets=["A股指数", "港股指数", "人民币汇率"],
        affectedSectors=["消费", "地产链", "互联网"],
        affectedThemes=["政策支持", "内需修复", "风险偏好"],
        implication="政策线索需要结合落地节奏、信用扩张与企业盈利改善证据观察。",
        confidence="needs_confirmation",
        evidenceQuality="placeholder",
        monitorNext=["政策细则", "信用扩张", "人民币方向"],
        relatedMacroVariables=["社融", "人民币汇率", "内需"],
        relatedResearchAreas=["中国政策周期", "内需修复"],
    ),
    HomepageEventImpactEvent(
        key="major_earnings_catalyst",
        label="大型企业业绩催化",
        observation="大型企业业绩或指引变化可能影响指数权重、行业预期与主题扩散。",
        affectedAssets=["指数权重股", "行业ETF", "主题篮子"],
        affectedSectors=["科技", "消费", "金融"],
        affectedThemes=["盈利质量", "指引变化", "主题扩散"],
        implication="业绩线索需要拆分收入质量、利润率、现金流与行业传导。",
        confidence="medium",
        evidenceQuality="placeholder",
        monitorNext=["收入质量", "利润率", "现金流"],
        relatedMacroVariables=["企业盈利", "消费需求", "融资条件"],
        relatedResearchAreas=["业绩周期", "行业传导"],
    ),
)


class HomepageEventImpactMapService:
    """Emit static impact-oriented event mapping without runtime dependencies."""

    def build_event_impact_map(self) -> dict[str, object]:
        payload = HomepageEventImpactMapResponse(
            schemaVersion=HOMEPAGE_EVENT_IMPACT_MAP_SCHEMA_VERSION,
            asOf=HOMEPAGE_EVENT_IMPACT_MAP_DEFAULT_AS_OF,
            eventWindow=HomepageEventImpactWindow(
                label="未来一周事件观察窗口",
                startsAt="2026-06-15",
                endsAt="2026-06-21",
                basis="固定占位样本，用于首页影响地图合约验证。",
            ),
            events=list(_EVENTS),
            affectedAssets=[
                "美债曲线",
                "美元指数",
                "股票指数",
                "原油",
                "黄金",
                "半导体指数",
                "人民币资产",
            ],
            affectedSectors=[
                "科技",
                "半导体",
                "能源",
                "金融",
                "消费",
                "交通运输",
                "地产链",
            ],
            affectedThemes=[
                "利率重新定价",
                "通胀路径",
                "AI基础设施",
                "供应链韧性",
                "油价风险溢价",
                "中国政策周期",
                "盈利质量",
            ],
            implication="事件影响地图用于把宏观、产业与企业催化映射到资产和主题观察。",
            confidence="scenario",
            evidenceQuality="placeholder",
            monitorNext=[
                "利率曲线变化",
                "美元方向",
                "能源价格",
                "供应链交付",
                "政策落地节奏",
                "业绩指引变化",
            ],
            relatedMacroVariables=[
                "政策利率预期",
                "核心通胀",
                "就业增长",
                "期限溢价",
                "能源价格",
                "美元指数",
                "人民币汇率",
            ],
            relatedResearchAreas=[
                "宏观政策路径",
                "通胀传导",
                "AI产业链",
                "半导体周期",
                "能源供需",
                "中国政策周期",
                "业绩周期",
            ],
            dataQuality=HomepageEventImpactDataQuality(
                status="placeholder",
                label="静态占位样本",
                available=True,
                summary="固定样本用于首页事件影响地图合约开发，不代表实时市场。",
            ),
            noAdviceDisclosure=HOMEPAGE_EVENT_IMPACT_MAP_NO_ADVICE_DISCLOSURE,
        )
        return payload.model_dump(mode="json")


__all__ = [
    "HOMEPAGE_EVENT_IMPACT_MAP_DEFAULT_AS_OF",
    "HOMEPAGE_EVENT_IMPACT_MAP_NO_ADVICE_DISCLOSURE",
    "HOMEPAGE_EVENT_IMPACT_MAP_SCHEMA_VERSION",
    "HomepageEventImpactMapService",
]
