# -*- coding: utf-8 -*-
"""Future-facing source-confidence contract boundary."""

from src.services.source_confidence_contract import (
    SOURCE_CONFIDENCE_CONTRACT_VERSION,
    SCORE_GRADE_BLOCKED_SOURCE_TYPES,
    SCORE_GRADE_TRUST_LEVELS,
    STRONG_FRESHNESS_VALUES,
    ProviderCapabilityContract,
    ProviderDryRunProbeContract,
    ProviderFitMetadataContract,
    ProviderCapabilitySupportContract,
    ScoreGradeSourceAuthorityResult,
    SourceConfidenceContract,
    SourceConfidenceValidationIssue,
    SourceConfidenceValidationResult,
    SourceFreshness,
    SupportsSourceConfidence,
    apply_source_confidence_caps,
    coerce_provider_capability_contract,
    coerce_provider_dry_run_probe_contract,
    coerce_provider_fit_metadata_contract,
    coerce_provider_capability_support_contract,
    coerce_source_confidence_contract,
    evaluate_score_grade_source_authority,
    validate_source_confidence_contract,
)
from src.services.market_intelligence_trust_gate import (
    MARKET_INTELLIGENCE_TRUST_GATE_VERSION,
    MarketIntelligenceSourceTier,
    MarketIntelligenceTrustLevel,
    MarketIntelligenceTrustResult,
    evaluate_market_intelligence_trust,
    evaluate_market_intelligence_trust_from_sources,
    resolve_market_intelligence_source_tier,
)

__all__ = [
    "MARKET_INTELLIGENCE_TRUST_GATE_VERSION",
    "SOURCE_CONFIDENCE_CONTRACT_VERSION",
    "SCORE_GRADE_BLOCKED_SOURCE_TYPES",
    "SCORE_GRADE_TRUST_LEVELS",
    "STRONG_FRESHNESS_VALUES",
    "MarketIntelligenceSourceTier",
    "MarketIntelligenceTrustLevel",
    "MarketIntelligenceTrustResult",
    "ProviderCapabilityContract",
    "ProviderDryRunProbeContract",
    "ProviderFitMetadataContract",
    "ProviderCapabilitySupportContract",
    "ScoreGradeSourceAuthorityResult",
    "SourceConfidenceContract",
    "SourceConfidenceValidationIssue",
    "SourceConfidenceValidationResult",
    "SourceFreshness",
    "SupportsSourceConfidence",
    "apply_source_confidence_caps",
    "coerce_provider_capability_contract",
    "coerce_provider_dry_run_probe_contract",
    "coerce_provider_fit_metadata_contract",
    "coerce_provider_capability_support_contract",
    "coerce_source_confidence_contract",
    "evaluate_score_grade_source_authority",
    "evaluate_market_intelligence_trust",
    "evaluate_market_intelligence_trust_from_sources",
    "resolve_market_intelligence_source_tier",
    "validate_source_confidence_contract",
]
