import type { PortfolioRiskResponse, PortfolioSnapshotResponse } from './portfolio';

const portfolioDiagnostics = {
  riskDiagnostics: {
    sourceAuthority: {
      state: 'manual',
      summary: 'Manual portfolio evidence',
      issues: [],
      details: { accountCount: 1 },
      source: 'portfolio_snapshot',
      sourceLabel: 'Portfolio snapshot',
      freshness: 'fresh',
      asOf: '2026-05-22',
    },
    fxFreshness: {
      state: 'stale',
      summary: 'FX rates need review',
      issues: [{ code: 'fx_rate_stale', label: 'FX rate stale', accountIds: [1] }],
      details: { stalePairCount: 1 },
      freshness: 'stale',
      asOf: '2026-05-21',
    },
    confidenceCap: {
      value: 60,
      decisionStatus: 'caution',
      reasonCodes: ['fx_rate_stale'],
      limitationLabels: ['FX rate stale'],
      disabledClaims: ['score_grade_claims'],
      policyVersion: 'portfolio_risk_confidence_cap_v1',
    },
  },
  portfolioRiskEvidence: {
    engine: 'portfolio_risk',
    runId: 'portfolio-risk:all:2026-05-22:fifo',
    evidenceVersion: 'ai_evidence_packet_v1',
    decisionStatus: 'caution',
    freshness: { asOf: '2026-05-22' },
    confidenceCap: {
      value: 60,
      policyVersion: 'confidence_cap_policy_v1',
      reasonCodes: ['fx_rate_stale'],
    },
    requiredEvidence: [
      {
        key: 'fx.rate',
        criticality: 'required',
        status: 'stale',
        valueClass: 'metadata',
        sourceRefIds: ['portfolio_snapshot'],
        asOf: '2026-05-21',
        freshnessClass: 'stale',
        reasonCodes: ['fx_rate_stale'],
      },
    ],
    sourceRefs: [
      {
        sourceRefId: 'portfolio_snapshot',
        provider: 'portfolio',
        category: 'positions',
        sourceClass: 'local',
        cacheHit: false,
        rawPayloadStored: false,
      },
    ],
    adminDiagnostics: {
      sanitizedOnly: true,
      rawPayloadStored: false,
    },
  },
  sourceAuthorityState: 'manual',
  valuationLineageState: 'price_fallback',
  fxFreshnessState: 'stale',
  holdingsLineageState: 'manual',
  cashLedgerCompletenessState: 'missing',
  benchmarkMappingState: 'missing',
  factorMappingState: 'missing',
  confidenceCap: {
    value: 60,
    decisionStatus: 'caution',
    reasonCodes: ['fx_rate_stale'],
    limitationLabels: ['FX rate stale'],
  },
};

export const portfolioSnapshotDiagnosticsTypeContract: PortfolioSnapshotResponse = {
  asOf: '2026-05-22',
  costMethod: 'fifo',
  currency: 'CNY',
  accountCount: 1,
  totalCash: 100,
  totalMarketValue: 200,
  totalEquity: 300,
  realizedPnl: 0,
  unrealizedPnl: 0,
  feeTotal: 0,
  taxTotal: 0,
  fxStale: true,
  accounts: [],
  ...portfolioDiagnostics,
};

export const portfolioRiskDiagnosticsTypeContract: PortfolioRiskResponse = {
  asOf: '2026-05-22',
  accountId: null,
  costMethod: 'fifo',
  currency: 'CNY',
  thresholds: {},
  concentration: {
    totalMarketValue: 200,
    topWeightPct: 100,
    alert: true,
    topPositions: [],
  },
  sectorConcentration: {
    totalMarketValue: 200,
    topWeightPct: 0,
    alert: false,
    topSectors: [],
    coverage: {},
    errors: [],
  },
  drawdown: {
    seriesPoints: 0,
    maxDrawdownPct: 0,
    currentDrawdownPct: 0,
    alert: false,
    fxStale: true,
  },
  stopLoss: {
    nearAlert: false,
    triggeredCount: 0,
    nearCount: 0,
    items: [],
  },
  ...portfolioDiagnostics,
};

export const portfolioDiagnosticsStateTypeContract = {
  snapshotValuationLineageState: portfolioSnapshotDiagnosticsTypeContract.valuationLineageState,
  snapshotSourceAuthorityState: portfolioSnapshotDiagnosticsTypeContract.sourceAuthorityState,
  snapshotFxFreshnessState: portfolioSnapshotDiagnosticsTypeContract.fxFreshnessState,
  snapshotHoldingsLineageState: portfolioSnapshotDiagnosticsTypeContract.holdingsLineageState,
  snapshotCashLedgerCompletenessState: portfolioSnapshotDiagnosticsTypeContract.cashLedgerCompletenessState,
  snapshotBenchmarkMappingState: portfolioSnapshotDiagnosticsTypeContract.benchmarkMappingState,
  snapshotFactorMappingState: portfolioSnapshotDiagnosticsTypeContract.factorMappingState,
  snapshotConfidenceCap: portfolioSnapshotDiagnosticsTypeContract.confidenceCap?.value,
  snapshotRiskDiagnostics: portfolioSnapshotDiagnosticsTypeContract.riskDiagnostics?.sourceAuthority?.state,
  snapshotRiskEvidenceSourceRefs: portfolioSnapshotDiagnosticsTypeContract.portfolioRiskEvidence?.sourceRefs?.length,
  riskValuationLineageState: portfolioRiskDiagnosticsTypeContract.valuationLineageState,
  riskSourceAuthorityState: portfolioRiskDiagnosticsTypeContract.sourceAuthorityState,
  riskFxFreshnessState: portfolioRiskDiagnosticsTypeContract.fxFreshnessState,
  riskHoldingsLineageState: portfolioRiskDiagnosticsTypeContract.holdingsLineageState,
  riskCashLedgerCompletenessState: portfolioRiskDiagnosticsTypeContract.cashLedgerCompletenessState,
  riskBenchmarkMappingState: portfolioRiskDiagnosticsTypeContract.benchmarkMappingState,
  riskFactorMappingState: portfolioRiskDiagnosticsTypeContract.factorMappingState,
  riskConfidenceCap: portfolioRiskDiagnosticsTypeContract.confidenceCap?.value,
  riskDiagnostics: portfolioRiskDiagnosticsTypeContract.riskDiagnostics?.fxFreshness?.freshness,
  riskEvidenceFreshness: portfolioRiskDiagnosticsTypeContract.portfolioRiskEvidence?.freshness?.asOf,
};
